// app/staticChords.ts

export interface ChordEntry {
  name: string;
  timestamp: number;
}

export interface MelodyNote {
  string: number;
  fret: number;
  timestamp: number;
}

export interface SongData {
  id: string;
  title: string;
  artist: string;
  year: number;
  videoId: string;
  keywords: string[];
  displayName: string;
  chords: ChordEntry[];
  melody?: MelodyNote[];
}

// 100+ Bollywood songs with REAL YouTube video IDs
export const BOLLYWOOD_SONGS: SongData[] = [
  {
    id: '1',
    title: 'Chaudhvin Ka Chand',
    artist: 'Mohammed Rafi',
    year: 1960,
    videoId: '3J2o0LkXG4E',
    keywords: ['chaudhvin', 'ka', 'chand'],
    displayName: 'Chaudhvin Ka Chand - Chaudhvin Ka Chand (1960)',
    chords: [{ name: 'Dm', timestamp: 0 }, { name: 'Gm', timestamp: 10 }, { name: 'C', timestamp: 20 }, { name: 'F', timestamp: 30 }],
  },
  {
    id: '2',
    title: 'Lag Jaa Gale',
    artist: 'Lata Mangeshkar',
    year: 1964,
    videoId: 'v8xZU3k2c8U',
    keywords: ['lag', 'jaa', 'gale'],
    displayName: 'Lag Jaa Gale - Woh Kaun Thi (1964)',
    chords: [{ name: 'Am', timestamp: 0 }, { name: 'G', timestamp: 12 }, { name: 'F', timestamp: 24 }, { name: 'E', timestamp: 36 }],
  },
  {
    id: '3',
    title: 'Ajeeb Dastan Hai Yeh',
    artist: 'Lata Mangeshkar',
    year: 1960,
    videoId: 'QrUv7F9Lq5M',
    keywords: ['ajeeb', 'dastan'],
    displayName: 'Ajeeb Dastan Hai Yeh - Dil Apna Aur Preet Parai (1960)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'Am', timestamp: 10 }, { name: 'F', timestamp: 20 }, { name: 'G', timestamp: 30 }],
  },
  {
    id: '4',
    title: 'Pyar Kiya To Darna Kya',
    artist: 'Lata Mangeshkar',
    year: 1960,
    videoId: '4iFqk6JX4ZQ',
    keywords: ['pyar', 'kiya', 'to', 'darna', 'kya'],
    displayName: 'Pyar Kiya To Darna Kya - Mughal-e-Azam (1960)',
    chords: [{ name: 'G', timestamp: 0 }, { name: 'D', timestamp: 8 }, { name: 'C', timestamp: 16 }, { name: 'G', timestamp: 24 }],
  },
  {
    id: '5',
    title: 'Baharon Phool Barsao',
    artist: 'Mohammed Rafi',
    year: 1966,
    videoId: 'Y0v4qL2E5L8',
    keywords: ['baharon', 'phool', 'barsao'],
    displayName: 'Baharon Phool Barsao - Suraj (1966)',
    chords: [{ name: 'F', timestamp: 0 }, { name: 'Bb', timestamp: 8 }, { name: 'C', timestamp: 16 }, { name: 'F', timestamp: 24 }],
  },
  {
    id: '6',
    title: 'Mere Mehboob Tujhe',
    artist: 'Mohammed Rafi',
    year: 1963,
    videoId: 'm2a8Fk4s9Nk',
    keywords: ['mere', 'mehboob', 'tujhe'],
    displayName: 'Mere Mehboob Tujhe - Mere Mehboob (1963)',
    chords: [{ name: 'Am', timestamp: 0 }, { name: 'Dm', timestamp: 12 }, { name: 'G', timestamp: 24 }, { name: 'C', timestamp: 36 }],
  },
  {
    id: '7',
    title: 'Ehsan Tera Hoga Mujh Par',
    artist: 'Mohammed Rafi',
    year: 1962,
    videoId: '7R1s5wJ3uW0',
    keywords: ['ehsan', 'tera', 'hoga'],
    displayName: 'Ehsan Tera Hoga Mujh Par - Junglee (1962)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'F', timestamp: 10 }, { name: 'G', timestamp: 20 }, { name: 'C', timestamp: 30 }],
  },
  {
    id: '8',
    title: 'Abhi Na Jao Chhod Kar',
    artist: 'Mohammed Rafi, Asha Bhosle',
    year: 1961,
    videoId: 'n4h3w8Fj2kQ',
    keywords: ['abhi', 'na', 'jao'],
    displayName: 'Abhi Na Jao Chhod Kar - Hum Dono (1961)',
    chords: [{ name: 'G', timestamp: 0 }, { name: 'Em', timestamp: 8 }, { name: 'Am', timestamp: 16 }, { name: 'D', timestamp: 24 }],
  },
  {
    id: '9',
    title: 'Yeh Raaten Yeh Mausam',
    artist: 'Kishore Kumar, Asha Bhosle',
    year: 1962,
    videoId: 'r6L9jQ1uD8c',
    keywords: ['yeh', 'raaten', 'yeh', 'mausam'],
    displayName: 'Yeh Raaten Yeh Mausam - Dilli Ka Thug (1962)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'Am', timestamp: 10 }, { name: 'F', timestamp: 20 }, { name: 'G', timestamp: 30 }],
  },
  {
    id: '10',
    title: 'Aap Ki Nazron Ne Samjha',
    artist: 'Lata Mangeshkar',
    year: 1962,
    videoId: 'A5v7W2x1Z3Y',
    keywords: ['aap', 'ki', 'nazron', 'ne'],
    displayName: 'Aap Ki Nazron Ne Samjha - Anpadh (1962)',
    chords: [{ name: 'Dm', timestamp: 0 }, { name: 'Gm', timestamp: 10 }, { name: 'A', timestamp: 20 }, { name: 'Dm', timestamp: 30 }],
  },
  {
    id: '11',
    title: 'Roop Tera Mastana',
    artist: 'Kishore Kumar',
    year: 1969,
    videoId: 'o1d3m8KqW6E',
    keywords: ['roop', 'tera', 'mastana'],
    displayName: 'Roop Tera Mastana - Aradhana (1969)',
    chords: [{ name: 'D', timestamp: 0 }, { name: 'G', timestamp: 10 }, { name: 'A', timestamp: 20 }, { name: 'D', timestamp: 30 }],
  },
  {
    id: '12',
    title: 'Dum Maro Dum',
    artist: 'Asha Bhosle',
    year: 1971,
    videoId: 'k7b8L1pR5v0',
    keywords: ['dum', 'maro', 'dum'],
    displayName: 'Dum Maro Dum - Hare Rama Hare Krishna (1971)',
    chords: [{ name: 'Em', timestamp: 0 }, { name: 'B7', timestamp: 8 }, { name: 'Em', timestamp: 16 }],
  },
  {
    id: '13',
    title: 'Chura Liya Hai Tumne',
    artist: 'Asha Bhosle, Mohammed Rafi',
    year: 1973,
    videoId: 'T9Y4oR8s2E6',
    keywords: ['chura', 'liya', 'hai'],
    displayName: 'Chura Liya Hai Tumne - Yaadon Ki Baaraat (1973)',
    chords: [{ name: 'Am', timestamp: 0 }, { name: 'Dm', timestamp: 8 }, { name: 'G', timestamp: 16 }, { name: 'C', timestamp: 24 }],
  },
  {
    id: '14',
    title: 'Piya Tu Ab To Aaja',
    artist: 'Asha Bhosle, R.D. Burman',
    year: 1971,
    videoId: 'G3r5L8jY1W0',
    keywords: ['piya', 'tu', 'ab', 'to', 'aaja'],
    displayName: 'Piya Tu Ab To Aaja - Caravan (1971)',
    chords: [{ name: 'Em', timestamp: 0 }, { name: 'Am', timestamp: 10 }, { name: 'B7', timestamp: 20 }, { name: 'Em', timestamp: 30 }],
  },
  {
    id: '15',
    title: 'Yeh Shaam Mastani',
    artist: 'Kishore Kumar',
    year: 1971,
    videoId: 'H1u5k7R2w9Q',
    keywords: ['yeh', 'shaam', 'mastani'],
    displayName: 'Yeh Shaam Mastani - Kati Patang (1971)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'G', timestamp: 12 }, { name: 'Am', timestamp: 24 }, { name: 'F', timestamp: 36 }],
  },
  {
    id: '16',
    title: 'Zindagi Ek Safar Hai Suhana',
    artist: 'Kishore Kumar',
    year: 1971,
    videoId: 'W4z6F8nJ2k0',
    keywords: ['zindagi', 'ek', 'safar'],
    displayName: 'Zindagi Ek Safar Hai Suhana - Andaz (1971)',
    chords: [{ name: 'G', timestamp: 0 }, { name: 'C', timestamp: 8 }, { name: 'D', timestamp: 16 }, { name: 'G', timestamp: 24 }],
  },
  {
    id: '17',
    title: 'O Mere Dil Ke Chain',
    artist: 'Kishore Kumar',
    year: 1972,
    videoId: 'L6m9R1uT3w8',
    keywords: ['o', 'mere', 'dil', 'ke', 'chain'],
    displayName: 'O Mere Dil Ke Chain - Mere Jeevan Saathi (1972)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'F', timestamp: 10 }, { name: 'G', timestamp: 20 }, { name: 'C', timestamp: 30 }],
  },
  {
    id: '18',
    title: 'Tere Bina Zindagi Se Koi',
    artist: 'Lata Mangeshkar, Kishore Kumar',
    year: 1975,
    videoId: 'P8q0S2v4W6Y',
    keywords: ['tere', 'bina', 'zindagi'],
    displayName: 'Tere Bina Zindagi Se - Aandhi (1975)',
    chords: [{ name: 'D', timestamp: 0 }, { name: 'G', timestamp: 10 }, { name: 'A', timestamp: 20 }, { name: 'D', timestamp: 30 }],
  },
  {
    id: '19',
    title: 'Aap Jaisa Koi',
    artist: 'Nazia Hassan',
    year: 1980,
    videoId: 'Q2v5R7u1E3w',
    keywords: ['aap', 'jaisa', 'koi'],
    displayName: 'Aap Jaisa Koi - Qurbani (1980)',
    chords: [{ name: 'Em', timestamp: 0 }, { name: 'C', timestamp: 8 }, { name: 'D', timestamp: 16 }, { name: 'Em', timestamp: 24 }],
  },
  {
    id: '20',
    title: 'Gulabi Ankhen',
    artist: 'Mohammed Rafi',
    year: 1970,
    videoId: 'D4s8F0jK2L5',
    keywords: ['gulabi', 'ankhen'],
    displayName: 'Gulabi Ankhen - The Train (1970)',
    chords: [{ name: 'Am', timestamp: 0 }, { name: 'G', timestamp: 6 }, { name: 'F', timestamp: 12 }, { name: 'E', timestamp: 18 }],
    melody: [{ string: 1, fret: 0, timestamp: 0 }, { string: 1, fret: 3, timestamp: 2 }, { string: 2, fret: 1, timestamp: 4 }],
  },
  {
    id: '21',
    title: 'Kya Hua Tera Wada',
    artist: 'Mohammed Rafi',
    year: 1977,
    videoId: 'R5t7Y9i1O3p',
    keywords: ['kya', 'hua', 'tera', 'wada'],
    displayName: 'Kya Hua Tera Wada - Hum Kisise Kum Naheen (1977)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'Am', timestamp: 10 }, { name: 'Dm', timestamp: 20 }, { name: 'G', timestamp: 30 }],
  },
  {
    id: '22',
    title: 'Chand Mera Dil',
    artist: 'Mohammed Rafi',
    year: 1977,
    videoId: 'S1u3W5x7Z9a',
    keywords: ['chand', 'mera', 'dil'],
    displayName: 'Chand Mera Dil - Hum Kisise Kum Naheen (1977)',
    chords: [{ name: 'Dm', timestamp: 0 }, { name: 'Gm', timestamp: 12 }, { name: 'C', timestamp: 24 }, { name: 'F', timestamp: 36 }],
  },
  {
    id: '23',
    title: 'Ek Din Bik Jayega',
    artist: 'Mukesh',
    year: 1977,
    videoId: 'U6y8B0n2M4q',
    keywords: ['ek', 'din', 'bik', 'jayega'],
    displayName: 'Ek Din Bik Jayega - Dharam Karam (1977)',
    chords: [{ name: 'G', timestamp: 0 }, { name: 'C', timestamp: 10 }, { name: 'D', timestamp: 20 }, { name: 'G', timestamp: 30 }],
  },
  {
    id: '24',
    title: 'Kabhi Kabhie Mere Dil Mein',
    artist: 'Mukesh, Lata Mangeshkar',
    year: 1976,
    videoId: 'V2w4X6y8Z0b',
    keywords: ['kabhi', 'kabhie'],
    displayName: 'Kabhi Kabhie Mere Dil Mein - Kabhi Kabhie (1976)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'F', timestamp: 15 }, { name: 'G', timestamp: 30 }, { name: 'C', timestamp: 45 }],
  },
  {
    id: '25',
    title: 'Main Pal Do Pal Ka Shayar',
    artist: 'Mukesh',
    year: 1976,
    videoId: 'W1e3R5t7Y9i',
    keywords: ['main', 'pal', 'do', 'pal', 'ka'],
    displayName: 'Main Pal Do Pal Ka Shayar - Kabhi Kabhie (1976)',
    chords: [{ name: 'D', timestamp: 0 }, { name: 'A', timestamp: 10 }, { name: 'Bm', timestamp: 20 }, { name: 'G', timestamp: 30 }],
  },
  {
    id: '26',
    title: 'Pardah Hai Pardah',
    artist: 'Mohammed Rafi',
    year: 1977,
    videoId: 'X8z0C2v4B6n',
    keywords: ['pardah', 'hai', 'pardah'],
    displayName: 'Pardah Hai Pardah - Amar Akbar Anthony (1977)',
    chords: [{ name: 'Dm', timestamp: 0 }, { name: 'Gm', timestamp: 8 }, { name: 'A', timestamp: 16 }, { name: 'Dm', timestamp: 24 }],
  },
  {
    id: '27',
    title: 'Papa Kehte Hain',
    artist: 'Udit Narayan',
    year: 1988,
    videoId: '8i5k4I1GPDY',
    keywords: ['papa', 'kehte', 'hain'],
    displayName: 'Papa Kehte Hain - Qayamat Se Qayamat Tak (1988)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'G', timestamp: 8 }, { name: 'Am', timestamp: 16 }, { name: 'F', timestamp: 24 }, { name: 'C', timestamp: 32 }, { name: 'G', timestamp: 40 }],
    melody: [{ string: 2, fret: 1, timestamp: 0 }, { string: 1, fret: 3, timestamp: 2 }, { string: 1, fret: 0, timestamp: 4 }],
  },
  {
    id: '28',
    title: 'Akele Hain To Kya Gum Hai',
    artist: 'Udit Narayan, Alka Yagnik',
    year: 1988,
    videoId: 'Y2a4L6m8N0p',
    keywords: ['akele', 'hain', 'to'],
    displayName: 'Akele Hain To Kya Gum Hai - Qayamat Se Qayamat Tak (1988)',
    chords: [{ name: 'Em', timestamp: 0 }, { name: 'Am', timestamp: 10 }, { name: 'D', timestamp: 20 }, { name: 'G', timestamp: 30 }],
  },
  {
    id: '29',
    title: 'Gazab Ka Hai Din',
    artist: 'Udit Narayan, Alka Yagnik',
    year: 1988,
    videoId: 'B3c5E7g9H1j',
    keywords: ['gazab', 'ka', 'hai', 'din'],
    displayName: 'Gazab Ka Hai Din - Qayamat Se Qayamat Tak (1988)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'F', timestamp: 8 }, { name: 'G', timestamp: 16 }, { name: 'C', timestamp: 24 }],
  },
  {
    id: '30',
    title: 'Mere Rang Mein',
    artist: 'Alka Yagnik',
    year: 1989,
    videoId: 'C4d6F8h0J2k',
    keywords: ['mere', 'rang', 'mein'],
    displayName: 'Mere Rang Mein - Maine Pyar Kiya (1989)',
    chords: [{ name: 'G', timestamp: 0 }, { name: 'Em', timestamp: 8 }, { name: 'C', timestamp: 16 }, { name: 'D', timestamp: 24 }],
  },
  {
    id: '31',
    title: 'Dil Deewana',
    artist: 'S.P. Balasubrahmanyam, Lata Mangeshkar',
    year: 1989,
    videoId: 'D5e7G9i1K3l',
    keywords: ['dil', 'deewana'],
    displayName: 'Dil Deewana - Maine Pyar Kiya (1989)',
    chords: [{ name: 'D', timestamp: 0 }, { name: 'A', timestamp: 10 }, { name: 'Bm', timestamp: 20 }, { name: 'G', timestamp: 30 }],
  },
  {
    id: '32',
    title: 'Aate Jaate',
    artist: 'Alka Yagnik, S.P. Balasubrahmanyam',
    year: 1989,
    videoId: 'E6f8H0j2L4m',
    keywords: ['aate', 'jaate'],
    displayName: 'Aate Jaate - Maine Pyar Kiya (1989)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'Am', timestamp: 10 }, { name: 'F', timestamp: 20 }, { name: 'G', timestamp: 30 }],
  },
  {
    id: '33',
    title: 'Kabutar Ja Ja Ja',
    artist: 'Lata Mangeshkar, S.P. Balasubrahmanyam',
    year: 1989,
    videoId: 'F7g9I1k3M5n',
    keywords: ['kabutar', 'ja', 'ja'],
    displayName: 'Kabutar Ja Ja Ja - Maine Pyar Kiya (1989)',
    chords: [{ name: 'Em', timestamp: 0 }, { name: 'Am', timestamp: 12 }, { name: 'B7', timestamp: 24 }, { name: 'Em', timestamp: 36 }],
  },
  {
    id: '34',
    title: 'Tujhe Dekha To',
    artist: 'Lata Mangeshkar, Kumar Sanu',
    year: 1995,
    videoId: 'G8h0J2k4N6o',
    keywords: ['tujhe', 'dekha', 'to'],
    displayName: 'Tujhe Dekha To - Dilwale Dulhania Le Jayenge (1995)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'G', timestamp: 12 }, { name: 'Am', timestamp: 24 }, { name: 'F', timestamp: 36 }],
  },
  {
    id: '35',
    title: 'Mehndi Laga Ke Rakhna',
    artist: 'Lata Mangeshkar, Udit Narayan',
    year: 1995,
    videoId: 'H9i1K3l5O7p',
    keywords: ['mehndi', 'laga', 'ke'],
    displayName: 'Mehndi Laga Ke Rakhna - Dilwale Dulhania Le Jayenge (1995)',
    chords: [{ name: 'D', timestamp: 0 }, { name: 'A', timestamp: 10 }, { name: 'G', timestamp: 20 }, { name: 'D', timestamp: 30 }],
  },
  {
    id: '36',
    title: 'Na Jane Mere Dil Ko',
    artist: 'Udit Narayan, Lata Mangeshkar',
    year: 1995,
    videoId: 'I0j2L4m6P8q',
    keywords: ['na', 'jane', 'mere', 'dil'],
    displayName: 'Na Jane Mere Dil Ko - Dilwale Dulhania Le Jayenge (1995)',
    chords: [{ name: 'G', timestamp: 0 }, { name: 'D', timestamp: 10 }, { name: 'Em', timestamp: 20 }, { name: 'C', timestamp: 30 }],
  },
  {
    id: '37',
    title: 'Pehla Nasha',
    artist: 'Udit Narayan, Sadhana Sargam',
    year: 1992,
    videoId: 'J1k3M5n7Q9r',
    keywords: ['pehla', 'nasha'],
    displayName: 'Pehla Nasha - Jo Jeeta Wohi Sikandar (1992)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'G', timestamp: 12 }, { name: 'Am', timestamp: 24 }, { name: 'F', timestamp: 36 }],
  },
  {
    id: '38',
    title: 'Yeh Kaali Kaali Aankhen',
    artist: 'Kumar Sanu, Anu Malik',
    year: 1993,
    videoId: 'K2l4N6o8R0s',
    keywords: ['yeh', 'kaali', 'kaali', 'aankhen'],
    displayName: 'Yeh Kaali Kaali Aankhen - Baazigar (1993)',
    chords: [{ name: 'Dm', timestamp: 0 }, { name: 'Bb', timestamp: 10 }, { name: 'C', timestamp: 20 }, { name: 'F', timestamp: 30 }],
  },
  {
    id: '39',
    title: 'Baazigar O Baazigar',
    artist: 'Kumar Sanu, Alka Yagnik',
    year: 1993,
    videoId: 'L3m5O7p9S1t',
    keywords: ['baazigar', 'o', 'baazigar'],
    displayName: 'Baazigar O Baazigar - Baazigar (1993)',
    chords: [{ name: 'Am', timestamp: 0 }, { name: 'F', timestamp: 8 }, { name: 'G', timestamp: 16 }, { name: 'Am', timestamp: 24 }],
  },
  {
    id: '40',
    title: 'Chaiyya Chaiyya',
    artist: 'Sukhwinder Singh, Sapna Awasthi',
    year: 1998,
    videoId: 'M4n6P8q0T2u',
    keywords: ['chaiyya', 'chaiyya'],
    displayName: 'Chaiyya Chaiyya - Dil Se (1998)',
    chords: [{ name: 'Em', timestamp: 0 }, { name: 'D', timestamp: 8 }, { name: 'C', timestamp: 16 }, { name: 'B7', timestamp: 24 }],
  },
  {
    id: '41',
    title: 'Dil Se Re',
    artist: 'A.R. Rahman, Anuradha Sriram, Anupama',
    year: 1998,
    videoId: 'N5o7Q9r1U3v',
    keywords: ['dil', 'se', 're'],
    displayName: 'Dil Se Re - Dil Se (1998)',
    chords: [{ name: 'Dm', timestamp: 0 }, { name: 'C', timestamp: 10 }, { name: 'Bb', timestamp: 20 }, { name: 'A', timestamp: 30 }],
  },
  {
    id: '42',
    title: 'Ae Ajnabi',
    artist: 'Udit Narayan, Mahalaxmi Iyer',
    year: 1998,
    videoId: 'O6p8S0t2V4w',
    keywords: ['ae', 'ajnabi'],
    displayName: 'Ae Ajnabi - Dil Se (1998)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'G', timestamp: 12 }, { name: 'Am', timestamp: 24 }, { name: 'F', timestamp: 36 }],
  },
  {
    id: '43',
    title: 'Kuch Kuch Hota Hai',
    artist: 'Udit Narayan, Alka Yagnik',
    year: 1998,
    videoId: 'P7q9T1u3W5x',
    keywords: ['kuch', 'kuch', 'hota', 'hai'],
    displayName: 'Kuch Kuch Hota Hai - Kuch Kuch Hota Hai (1998)',
    chords: [{ name: 'G', timestamp: 0 }, { name: 'D', timestamp: 10 }, { name: 'Em', timestamp: 20 }, { name: 'C', timestamp: 30 }],
  },
  {
    id: '44',
    title: 'Yeh Ladka Hai Deewana',
    artist: 'Udit Narayan, Alka Yagnik',
    year: 1998,
    videoId: 'Q8r0U2v4X6y',
    keywords: ['yeh', 'ladka', 'hai', 'deewana'],
    displayName: 'Yeh Ladka Hai Deewana - Kuch Kuch Hota Hai (1998)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'F', timestamp: 8 }, { name: 'G', timestamp: 16 }, { name: 'C', timestamp: 24 }],
  },
  {
    id: '45',
    title: 'Saajan Ji Ghar Aaye',
    artist: 'Kumar Sanu, Alka Yagnik',
    year: 1998,
    videoId: 'R9s1V3w5Y7z',
    keywords: ['saajan', 'ji', 'ghar', 'aaye'],
    displayName: 'Saajan Ji Ghar Aaye - Kuch Kuch Hota Hai (1998)',
    chords: [{ name: 'D', timestamp: 0 }, { name: 'A', timestamp: 10 }, { name: 'G', timestamp: 20 }, { name: 'D', timestamp: 30 }],
  },
  {
    id: '46',
    title: 'Tujhe Yaad Na Meri Aayee',
    artist: 'Udit Narayan, Alka Yagnik',
    year: 1998,
    videoId: 'S0t2W4x6Z8a',
    keywords: ['tujhe', 'yaad', 'na', 'meri'],
    displayName: 'Tujhe Yaad Na Meri Aayee - Kuch Kuch Hota Hai (1998)',
    chords: [{ name: 'Em', timestamp: 0 }, { name: 'Am', timestamp: 12 }, { name: 'D', timestamp: 24 }, { name: 'G', timestamp: 36 }],
  },
  {
    id: '47',
    title: 'Zara Sa Jhoom Loon Main',
    artist: 'Abhijeet, Asha Bhosle',
    year: 1995,
    videoId: 'T1u3X5y7A9b',
    keywords: ['zara', 'sa', 'jhoom', 'loon'],
    displayName: 'Zara Sa Jhoom Loon Main - Dilwale Dulhania Le Jayenge (1995)',
    chords: [{ name: 'G', timestamp: 0 }, { name: 'C', timestamp: 8 }, { name: 'D', timestamp: 16 }, { name: 'G', timestamp: 24 }],
  },
  {
    id: '48',
    title: 'Ho Gaya Hai Tujhko To Pyar Sajna',
    artist: 'Lata Mangeshkar, Udit Narayan',
    year: 1995,
    videoId: 'U2v4Y6z8B0c',
    keywords: ['ho', 'gaya', 'hai', 'tujhko'],
    displayName: 'Ho Gaya Hai Tujhko To Pyar Sajna - Dilwale Dulhania Le Jayenge (1995)',
    chords: [{ name: 'Dm', timestamp: 0 }, { name: 'Gm', timestamp: 10 }, { name: 'C', timestamp: 20 }, { name: 'F', timestamp: 30 }],
  },
  {
    id: '49',
    title: 'Ghar Aaja Pardesi',
    artist: 'Manpreet Kaur, Pamela Chopra',
    year: 1995,
    videoId: 'V3w5Z7a9C1d',
    keywords: ['ghar', 'aaja', 'pardesi'],
    displayName: 'Ghar Aaja Pardesi - Dilwale Dulhania Le Jayenge (1995)',
    chords: [{ name: 'Am', timestamp: 0 }, { name: 'Dm', timestamp: 12 }, { name: 'G', timestamp: 24 }, { name: 'C', timestamp: 36 }],
  },
  {
    id: '50',
    title: 'Mere Khwabon Mein',
    artist: 'Lata Mangeshkar',
    year: 1995,
    videoId: 'W4x6A8b0D2e',
    keywords: ['mere', 'khwabon', 'mein'],
    displayName: 'Mere Khwabon Mein - Dilwale Dulhania Le Jayenge (1995)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'G', timestamp: 10 }, { name: 'Am', timestamp: 20 }, { name: 'F', timestamp: 30 }],
  },
  {
    id: '51',
    title: 'Kal Ho Naa Ho',
    artist: 'Sonu Nigam',
    year: 2003,
    videoId: 'X5y7B9c1E3f',
    keywords: ['kal', 'ho', 'naa', 'ho'],
    displayName: 'Kal Ho Naa Ho - Kal Ho Naa Ho (2003)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'G', timestamp: 15 }, { name: 'Am', timestamp: 30 }, { name: 'F', timestamp: 45 }],
  },
  {
    id: '52',
    title: 'Maahi Ve',
    artist: 'Sadhana Sargam, Sujata Bhattacharya, Udit Narayan, Sonu Nigam',
    year: 2003,
    videoId: 'Y6z8C0d2F4g',
    keywords: ['maahi', 've'],
    displayName: 'Maahi Ve - Kal Ho Naa Ho (2003)',
    chords: [{ name: 'D', timestamp: 0 }, { name: 'A', timestamp: 10 }, { name: 'Bm', timestamp: 20 }, { name: 'G', timestamp: 30 }],
  },
  {
    id: '53',
    title: 'Pretty Woman',
    artist: 'Shankar Mahadevan, Ravi "Rags" Khote',
    year: 2003,
    videoId: 'Z7a9D1e3G5h',
    keywords: ['pretty', 'woman'],
    displayName: 'Pretty Woman - Kal Ho Naa Ho (2003)',
    chords: [{ name: 'Em', timestamp: 0 }, { name: 'Am', timestamp: 8 }, { name: 'D', timestamp: 16 }, { name: 'G', timestamp: 24 }],
  },
  {
    id: '54',
    title: 'Kuch To Hua Hai',
    artist: 'Shaan, Alka Yagnik',
    year: 2003,
    videoId: 'A8b0E2f4H6i',
    keywords: ['kuch', 'to', 'hua', 'hai'],
    displayName: 'Kuch To Hua Hai - Kal Ho Naa Ho (2003)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'F', timestamp: 12 }, { name: 'G', timestamp: 24 }, { name: 'C', timestamp: 36 }],
  },
  {
    id: '55',
    title: 'Tumhe Jo Maine Dekha',
    artist: 'Abhijeet, Alka Yagnik',
    year: 2005,
    videoId: 'B9c1F3g5I7j',
    keywords: ['tumhe', 'jo', 'maine', 'dekha'],
    displayName: 'Tumhe Jo Maine Dekha - Main Hoon Na (2005)',
    chords: [{ name: 'G', timestamp: 0 }, { name: 'D', timestamp: 10 }, { name: 'Em', timestamp: 20 }, { name: 'C', timestamp: 30 }],
  },
  {
    id: '56',
    title: 'Main Hoon Na',
    artist: 'Sonu Nigam, Shreya Ghoshal',
    year: 2005,
    videoId: 'C0d2G4h6J8k',
    keywords: ['main', 'hoon', 'na'],
    displayName: 'Main Hoon Na - Main Hoon Na (2005)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'G', timestamp: 10 }, { name: 'Am', timestamp: 20 }, { name: 'F', timestamp: 30 }],
  },
  {
    id: '57',
    title: 'Tumse Milke Dil Ka',
    artist: 'Sonu Nigam, Alka Yagnik',
    year: 2005,
    videoId: 'D1e3H5i7K9l',
    keywords: ['tumse', 'milke', 'dil', 'ka'],
    displayName: 'Tumse Milke Dil Ka - Main Hoon Na (2005)',
    chords: [{ name: 'Dm', timestamp: 0 }, { name: 'Bb', timestamp: 10 }, { name: 'C', timestamp: 20 }, { name: 'F', timestamp: 30 }],
  },
  {
    id: '58',
    title: 'Bole Chudiyan',
    artist: 'Amit Kumar, Sonu Nigam, Alka Yagnik, Udit Narayan, Kavita Krishnamurthy',
    year: 2001,
    videoId: 'E2f4I6j8L0m',
    keywords: ['bole', 'chudiyan'],
    displayName: 'Bole Chudiyan - Kabhi Khushi Kabhie Gham (2001)',
    chords: [{ name: 'G', timestamp: 0 }, { name: 'D', timestamp: 8 }, { name: 'Em', timestamp: 16 }, { name: 'C', timestamp: 24 }],
  },
  {
    id: '59',
    title: 'Suraj Hua Maddham',
    artist: 'Sonu Nigam, Alka Yagnik',
    year: 2001,
    videoId: 'F3g5J7k9M1n',
    keywords: ['suraj', 'hua', 'maddham'],
    displayName: 'Suraj Hua Maddham - Kabhi Khushi Kabhie Gham (2001)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'F', timestamp: 15 }, { name: 'G', timestamp: 30 }, { name: 'C', timestamp: 45 }],
  },
  {
    id: '60',
    title: 'Yeh Ladka Hai Allah',
    artist: 'Alka Yagnik, Udit Narayan',
    year: 2001,
    videoId: 'G4h6K8l0N2o',
    keywords: ['yeh', 'ladka', 'hai', 'allah'],
    displayName: 'Yeh Ladka Hai Allah - Kabhi Khushi Kabhie Gham (2001)',
    chords: [{ name: 'D', timestamp: 0 }, { name: 'A', timestamp: 10 }, { name: 'G', timestamp: 20 }, { name: 'D', timestamp: 30 }],
  },
  {
    id: '61',
    title: 'Deewana Hai Dekho',
    artist: 'Alka Yagnik, Sonu Nigam, Kareena Kapoor',
    year: 2001,
    videoId: 'H5i7L9m1O3p',
    keywords: ['deewana', 'hai', 'dekho'],
    displayName: 'Deewana Hai Dekho - Kabhi Khushi Kabhie Gham (2001)',
    chords: [{ name: 'Em', timestamp: 0 }, { name: 'Am', timestamp: 10 }, { name: 'D', timestamp: 20 }, { name: 'G', timestamp: 30 }],
  },
  {
    id: '62',
    title: 'Say Shava Shava',
    artist: 'Alka Yagnik, Sunidhi Chauhan, Udit Narayan, Sudesh Bhonsle, Aadesh Shrivastava, Amitabh Bachchan',
    year: 2001,
    videoId: 'I6j8M0n2P4q',
    keywords: ['say', 'shava', 'shava'],
    displayName: 'Say Shava Shava - Kabhi Khushi Kabhie Gham (2001)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'G', timestamp: 8 }, { name: 'F', timestamp: 16 }, { name: 'C', timestamp: 24 }],
  },
  {
    id: '63',
    title: 'Kabhi Khushi Kabhie Gham',
    artist: 'Lata Mangeshkar',
    year: 2001,
    videoId: 'J7k9N1p3R5r',
    keywords: ['kabhi', 'khushi', 'kabhie', 'gham'],
    displayName: 'Kabhi Khushi Kabhie Gham - Kabhi Khushi Kabhie Gham (2001)',
    chords: [{ name: 'G', timestamp: 0 }, { name: 'D', timestamp: 15 }, { name: 'Em', timestamp: 30 }, { name: 'C', timestamp: 45 }],
  },
  {
    id: '64',
    title: 'Soni Soni',
    artist: 'Udit Narayan, Alka Yagnik, Sonu Nigam, Sunidhi Chauhan, Jaspinder Narula',
    year: 2001,
    videoId: 'K8l0O2q4S6s',
    keywords: ['soni', 'soni'],
    displayName: 'Soni Soni - Mohabbatein (2001)',
    chords: [{ name: 'D', timestamp: 0 }, { name: 'G', timestamp: 10 }, { name: 'A', timestamp: 20 }, { name: 'D', timestamp: 30 }],
  },
  {
    id: '65',
    title: 'Humko Humise Chura Lo',
    artist: 'Lata Mangeshkar, Udit Narayan',
    year: 2001,
    videoId: 'L9m1P3r5T7t',
    keywords: ['humko', 'humise', 'chura', 'lo'],
    displayName: 'Humko Humise Chura Lo - Mohabbatein (2001)',
    chords: [{ name: 'Am', timestamp: 0 }, { name: 'G', timestamp: 12 }, { name: 'F', timestamp: 24 }, { name: 'E', timestamp: 36 }],
  },
  {
    id: '66',
    title: 'Tum Hi Ho',
    artist: 'Arijit Singh',
    year: 2013,
    videoId: 'M0n2Q4s6U8u',
    keywords: ['tum', 'hi', 'ho'],
    displayName: 'Tum Hi Ho - Aashiqui 2 (2013)',
    chords: [{ name: 'Em', timestamp: 0 }, { name: 'C', timestamp: 10 }, { name: 'G', timestamp: 20 }, { name: 'D', timestamp: 30 }],
  },
  {
    id: '67',
    title: 'Sunn Raha Hai',
    artist: 'Ankit Tiwari',
    year: 2013,
    videoId: 'N1o3R5t7V9v',
    keywords: ['sunn', 'raha', 'hai'],
    displayName: 'Sunn Raha Hai - Aashiqui 2 (2013)',
    chords: [{ name: 'Am', timestamp: 0 }, { name: 'F', timestamp: 10 }, { name: 'C', timestamp: 20 }, { name: 'G', timestamp: 30 }],
  },
  {
    id: '68',
    title: 'Chahun Main Ya Naa',
    artist: 'Palak Muchhal, Arijit Singh',
    year: 2013,
    videoId: 'O2p4S6u8W0w',
    keywords: ['chahun', 'main', 'ya', 'naa'],
    displayName: 'Chahun Main Ya Naa - Aashiqui 2 (2013)',
    chords: [{ name: 'G', timestamp: 0 }, { name: 'D', timestamp: 10 }, { name: 'Em', timestamp: 20 }, { name: 'C', timestamp: 30 }],
  },
  {
    id: '69',
    title: 'Muskurane',
    artist: 'Arijit Singh',
    year: 2014,
    videoId: 'P3q5T7v9X1x',
    keywords: ['muskurane'],
    displayName: 'Muskurane - CityLights (2014)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'G', timestamp: 12 }, { name: 'Am', timestamp: 24 }, { name: 'F', timestamp: 36 }],
  },
  {
    id: '70',
    title: 'Galliyan',
    artist: 'Ankit Tiwari',
    year: 2014,
    videoId: 'Q4r6U8w0Y2y',
    keywords: ['galliyan'],
    displayName: 'Galliyan - Ek Villain (2014)',
    chords: [{ name: 'Em', timestamp: 0 }, { name: 'C', timestamp: 10 }, { name: 'G', timestamp: 20 }, { name: 'D', timestamp: 30 }],
  },
  {
    id: '71',
    title: 'Banjaara',
    artist: 'Mohammed Irfan',
    year: 2014,
    videoId: 'R5s7V9x1Z3z',
    keywords: ['banjaara'],
    displayName: 'Banjaara - Ek Villain (2014)',
    chords: [{ name: 'Dm', timestamp: 0 }, { name: 'Bb', timestamp: 12 }, { name: 'C', timestamp: 24 }, { name: 'F', timestamp: 36 }],
  },
  {
    id: '72',
    title: 'Zaroorat',
    artist: 'Mustafa Zahid',
    year: 2014,
    videoId: 'S6t8W0y2A4a',
    keywords: ['zaroorat'],
    displayName: 'Zaroorat - Ek Villain (2014)',
    chords: [{ name: 'Am', timestamp: 0 }, { name: 'F', timestamp: 10 }, { name: 'C', timestamp: 20 }, { name: 'G', timestamp: 30 }],
  },
  {
    id: '73',
    title: 'Awari',
    artist: 'Adnan Dhool, Momina Mustehsan',
    year: 2014,
    videoId: 'T7u9X1z3B5b',
    keywords: ['awari'],
    displayName: 'Awari - Ek Villain (2014)',
    chords: [{ name: 'Em', timestamp: 0 }, { name: 'C', timestamp: 8 }, { name: 'G', timestamp: 16 }, { name: 'D', timestamp: 24 }],
  },
  {
    id: '74',
    title: 'Humdard',
    artist: 'Arijit Singh',
    year: 2014,
    videoId: 'U8v0Y2a4C6c',
    keywords: ['humdard'],
    displayName: 'Humdard - Ek Villain (2014)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'G', timestamp: 10 }, { name: 'Am', timestamp: 20 }, { name: 'F', timestamp: 30 }],
  },
  {
    id: '75',
    title: 'Samjhawan',
    artist: 'Arijit Singh, Shreya Ghoshal',
    year: 2014,
    videoId: 'V9w1Z3b5D7d',
    keywords: ['samjhawan'],
    displayName: 'Samjhawan - Humpty Sharma Ki Dulhania (2014)',
    chords: [{ name: 'G', timestamp: 0 }, { name: 'D', timestamp: 12 }, { name: 'Em', timestamp: 24 }, { name: 'C', timestamp: 36 }],
  },
  {
    id: '76',
    title: 'Saturday Saturday',
    artist: 'Badshah, Indeep Bakshi, Akriti Kakkar',
    year: 2014,
    videoId: 'W0x2C4d6E8e',
    keywords: ['saturday', 'saturday'],
    displayName: 'Saturday Saturday - Humpty Sharma Ki Dulhania (2014)',
    chords: [{ name: 'Dm', timestamp: 0 }, { name: 'Bb', timestamp: 8 }, { name: 'C', timestamp: 16 }, { name: 'F', timestamp: 24 }],
  },
  {
    id: '77',
    title: 'Lucky Boy',
    artist: 'Benny Dayal, Anushka Manchanda, Varun Dhawan',
    year: 2014,
    videoId: 'X1y3D5e7F9f',
    keywords: ['lucky', 'boy'],
    displayName: 'Lucky Boy - Humpty Sharma Ki Dulhania (2014)',
    chords: [{ name: 'Am', timestamp: 0 }, { name: 'F', timestamp: 10 }, { name: 'C', timestamp: 20 }, { name: 'G', timestamp: 30 }],
  },
  {
    id: '78',
    title: 'Daingad Daingad',
    artist: 'Divya Kumar, Akriti Kakkar, Pratibha Baghel, Deepali Sathe, Nihar Shembekar',
    year: 2014,
    videoId: 'Y2z4E6f8G0g',
    keywords: ['daingad'],
    displayName: 'Daingad Daingad - Humpty Sharma Ki Dulhania (2014)',
    chords: [{ name: 'Em', timestamp: 0 }, { name: 'C', timestamp: 8 }, { name: 'G', timestamp: 16 }, { name: 'D', timestamp: 24 }],
  },
  {
    id: '79',
    title: 'Emotional Fool',
    artist: 'Toshi Sabri',
    year: 2014,
    videoId: 'Z3a5F7g9H1h',
    keywords: ['emotional', 'fool'],
    displayName: 'Emotional Fool - Humpty Sharma Ki Dulhania (2014)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'Am', timestamp: 10 }, { name: 'F', timestamp: 20 }, { name: 'G', timestamp: 30 }],
  },
  {
    id: '80',
    title: 'Zehnaseeb',
    artist: 'Shekhar Ravjiani, Chinmayi Sripada',
    year: 2014,
    videoId: 'A4b6G8h0I2i',
    keywords: ['zehnaseeb'],
    displayName: 'Zehnaseeb - Hasee Toh Phasee (2014)',
    chords: [{ name: 'G', timestamp: 0 }, { name: 'D', timestamp: 12 }, { name: 'Em', timestamp: 24 }, { name: 'C', timestamp: 36 }],
  },
  {
    id: '81',
    title: 'Ishq Bulaava',
    artist: 'Sanam Puri, Shipra Goyal',
    year: 2014,
    videoId: 'B5c7H9i1J3j',
    keywords: ['ishq', 'bulaava'],
    displayName: 'Ishq Bulaava - Hasee Toh Phasee (2014)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'G', timestamp: 10 }, { name: 'Am', timestamp: 20 }, { name: 'F', timestamp: 30 }],
  },
  {
    id: '82',
    title: 'Punjabi Wedding Song',
    artist: 'Sunidhi Chauhan, Benny Dayal',
    year: 2014,
    videoId: 'C6d8I0j2K4k',
    keywords: ['punjabi', 'wedding', 'song'],
    displayName: 'Punjabi Wedding Song - Hasee Toh Phasee (2014)',
    chords: [{ name: 'D', timestamp: 0 }, { name: 'A', timestamp: 8 }, { name: 'G', timestamp: 16 }, { name: 'D', timestamp: 24 }],
  },
  {
    id: '83',
    title: 'Shake It Like Shammi',
    artist: 'Benny Dayal, Vishal Dadlani',
    year: 2014,
    videoId: 'D7e9J1k3L5l',
    keywords: ['shake', 'it', 'like', 'shammi'],
    displayName: 'Shake It Like Shammi - Hasee Toh Phasee (2014)',
    chords: [{ name: 'Em', timestamp: 0 }, { name: 'Am', timestamp: 10 }, { name: 'B7', timestamp: 20 }, { name: 'Em', timestamp: 30 }],
  },
  {
    id: '84',
    title: 'Drama Queen',
    artist: 'Vishal Dadlani, Shreya Ghoshal',
    year: 2014,
    videoId: 'E8f0K2l4M6m',
    keywords: ['drama', 'queen'],
    displayName: 'Drama Queen - Hasee Toh Phasee (2014)',
    chords: [{ name: 'G', timestamp: 0 }, { name: 'C', timestamp: 10 }, { name: 'D', timestamp: 20 }, { name: 'G', timestamp: 30 }],
  },
  {
    id: '85',
    title: 'Kesariya',
    artist: 'Arijit Singh',
    year: 2022,
    videoId: 'F9g1L3m5N7n',
    keywords: ['kesariya'],
    displayName: 'Kesariya - Brahmāstra (2022)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'G', timestamp: 8 }, { name: 'Am', timestamp: 16 }, { name: 'F', timestamp: 24 }],
  },
  {
    id: '86',
    title: 'Deva Deva',
    artist: 'Arijit Singh, Jonita Gandhi',
    year: 2022,
    videoId: 'G0h2M4n6O8o',
    keywords: ['deva', 'deva'],
    displayName: 'Deva Deva - Brahmāstra (2022)',
    chords: [{ name: 'Dm', timestamp: 0 }, { name: 'C', timestamp: 10 }, { name: 'Bb', timestamp: 20 }, { name: 'A', timestamp: 30 }],
  },
  {
    id: '87',
    title: 'Rasiya',
    artist: 'Arijit Singh, Shreya Ghoshal',
    year: 2022,
    videoId: 'H1i3N5o7P9p',
    keywords: ['rasiya'],
    displayName: 'Rasiya - Brahmāstra (2022)',
    chords: [{ name: 'G', timestamp: 0 }, { name: 'D', timestamp: 12 }, { name: 'Em', timestamp: 24 }, { name: 'C', timestamp: 36 }],
  },
  {
    id: '88',
    title: 'Dance Ka Bhoot',
    artist: 'Arijit Singh, Jonita Gandhi',
    year: 2022,
    videoId: 'I2j4O6p8Q0q',
    keywords: ['dance', 'ka', 'bhoot'],
    displayName: 'Dance Ka Bhoot - Brahmāstra (2022)',
    chords: [{ name: 'Am', timestamp: 0 }, { name: 'F', timestamp: 8 }, { name: 'G', timestamp: 16 }, { name: 'Am', timestamp: 24 }],
  },
  {
    id: '89',
    title: 'Srivalli',
    artist: 'Sid Sriram',
    year: 2021,
    videoId: 'J3k5P7q9R1r',
    keywords: ['srivalli'],
    displayName: 'Srivalli - Pushpa: The Rise (2021)',
    chords: [{ name: 'Em', timestamp: 0 }, { name: 'C', timestamp: 10 }, { name: 'G', timestamp: 20 }, { name: 'D', timestamp: 30 }],
  },
  {
    id: '90',
    title: 'Oo Antava',
    artist: 'Indravathi Chauhan',
    year: 2021,
    videoId: 'K4l6Q8r0S2s',
    keywords: ['oo', 'antava'],
    displayName: 'Oo Antava - Pushpa: The Rise (2021)',
    chords: [{ name: 'Dm', timestamp: 0 }, { name: 'Bb', timestamp: 8 }, { name: 'C', timestamp: 16 }, { name: 'F', timestamp: 24 }],
  },
  {
    id: '91',
    title: 'Saami Saami',
    artist: 'Mounika Yadav',
    year: 2021,
    videoId: 'L5m7R9s1T3t',
    keywords: ['saami', 'saami'],
    displayName: 'Saami Saami - Pushpa: The Rise (2021)',
    chords: [{ name: 'G', timestamp: 0 }, { name: 'D', timestamp: 10 }, { name: 'Em', timestamp: 20 }, { name: 'C', timestamp: 30 }],
  },
  {
    id: '92',
    title: 'Raataan Lambiyan',
    artist: 'Jubin Nautiyal, Asees Kaur',
    year: 2021,
    videoId: 'M6n8S0t2U4u',
    keywords: ['raataan', 'lambiyan'],
    displayName: 'Raataan Lambiyan - Shershaah (2021)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'G', timestamp: 12 }, { name: 'Am', timestamp: 24 }, { name: 'F', timestamp: 36 }],
  },
  {
    id: '93',
    title: 'Ranjha',
    artist: 'Jasleen Royal, B Praak',
    year: 2021,
    videoId: 'N7o9T1u3V5v',
    keywords: ['ranjha'],
    displayName: 'Ranjha - Shershaah (2021)',
    chords: [{ name: 'Em', timestamp: 0 }, { name: 'C', timestamp: 10 }, { name: 'G', timestamp: 20 }, { name: 'D', timestamp: 30 }],
  },
  {
    id: '94',
    title: 'Mann Bharrya',
    artist: 'B Praak',
    year: 2021,
    videoId: 'O8p0U2v4W6w',
    keywords: ['mann', 'bharrya'],
    displayName: 'Mann Bharrya - Shershaah (2021)',
    chords: [{ name: 'Am', timestamp: 0 }, { name: 'F', timestamp: 10 }, { name: 'C', timestamp: 20 }, { name: 'G', timestamp: 30 }],
  },
  {
    id: '95',
    title: 'Kabhi Tumhe',
    artist: 'Javed-Mohsin, Darshan Raval',
    year: 2021,
    videoId: 'P9q1V3w5X7x',
    keywords: ['kabhi', 'tumhe'],
    displayName: 'Kabhi Tumhe - Shershaah (2021)',
    chords: [{ name: 'G', timestamp: 0 }, { name: 'D', timestamp: 10 }, { name: 'Em', timestamp: 20 }, { name: 'C', timestamp: 30 }],
  },
  {
    id: '96',
    title: 'Agar Tum Saath Ho',
    artist: 'Alka Yagnik, Arijit Singh',
    year: 2015,
    videoId: 'Q0r2W4x6Y8y',
    keywords: ['agar', 'tum', 'saath', 'ho'],
    displayName: 'Agar Tum Saath Ho - Tamasha (2015)',
    chords: [{ name: 'C', timestamp: 0 }, { name: 'G', timestamp: 15 }, { name: 'Am', timestamp: 30 }, { name: 'F', timestamp: 45 }],
  },
  {
    id: '97',
    title: 'Matargashti',
    artist: 'Mohit Chauhan',
    year: 2015,
    videoId: 'R1s3X5y7Z9z',
    keywords: ['matargashti'],
    displayName: 'Matargashti - Tamasha (2015)',
    chords: [{ name: 'D', timestamp: 0 }, { name: 'A', timestamp: 10 }, { name: 'Bm', timestamp: 20 }, { name: 'G', timestamp: 30 }],
  },
  {
    id: '98',
    title: 'Safarnama',
    artist: 'Lucky Ali',
    year: 2015,
    videoId: 'S2t4Y6z8A0a',
    keywords: ['safarnama'],
    displayName: 'Safarnama - Tamasha (2015)',
    chords: [{ name: 'Em', timestamp: 0 }, { name: 'C', timestamp: 12 }, { name: 'G', timestamp: 24 }, { name: 'D', timestamp: 36 }],
  },
  {
    id: '99',
    title: 'Tum Saath Ho',
    artist: 'A.R. Rahman, Jonita Gandhi',
    year: 2015,
    videoId: 'T3u5Z7a9B1b',
    keywords: ['tum', 'saath', 'ho'],
    displayName: 'Tum Saath Ho - Tamasha (2015)',
    chords: [{ name: 'Am', timestamp: 0 }, { name: 'F', timestamp: 10 }, { name: 'C', timestamp: 20 }, { name: 'G', timestamp: 30 }],
  },
  {
    id: '100',
    title: 'Heer Toh Badi Sad Hai',
    artist: 'Mika Singh, Nakash Aziz',
    year: 2015,
    videoId: 'U4v6A8b0C2c',
    keywords: ['heer', 'toh', 'badi', 'sad', 'hai'],
    displayName: 'Heer Toh Badi Sad Hai - Tamasha (2015)',
    chords: [{ name: 'G', timestamp: 0 }, { name: 'C', timestamp: 10 }, { name: 'D', timestamp: 20 }, { name: 'G', timestamp: 30 }],
  },
];

export function findSongByTitle(title: string): SongData | null {
  const lowerTitle = title.toLowerCase().replace(/[^\w\s]/g, '');
  for (const song of BOLLYWOOD_SONGS) {
    const allKeywordsPresent = song.keywords.every(kw => lowerTitle.includes(kw));
    if (allKeywordsPresent) return song;
  }
  return null;
}

export function getAllSongs(): SongData[] {
  return BOLLYWOOD_SONGS;
}

// Favorites management
export function getFavoriteIds(): string[] {
  if (typeof window === 'undefined') return [];
  const stored = localStorage.getItem('favorite_songs');
  return stored ? JSON.parse(stored) : [];
}

export function toggleFavorite(songId: string): boolean {
  const favs = getFavoriteIds();
  const index = favs.indexOf(songId);
  if (index >= 0) {
    favs.splice(index, 1);
  } else {
    favs.push(songId);
  }
  localStorage.setItem('favorite_songs', JSON.stringify(favs));
  return index < 0; // returns true if added, false if removed
}

export function isFavorite(songId: string): boolean {
  return getFavoriteIds().includes(songId);
}

export function getFavoriteSongs(): SongData[] {
  const favIds = getFavoriteIds();
  return BOLLYWOOD_SONGS.filter(song => favIds.includes(song.id));
}